# Generated by Django 2.0.6 on 2018-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='object_id',
        ),
        migrations.AddField(
            model_name='event',
            name='object_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
