# Generated by Django 2.0.6 on 2018-06-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='object_url',
            new_name='object_id',
        ),
    ]
