# Generated by Django 2.0.6 on 2018-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='day',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='month_id',
            new_name='calendar_id',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.ManyToManyField(to='userscalendar.Day'),
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
