# Generated by Django 2.0.6 on 2018-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0002_auto_20180623_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_in_month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
