# Generated by Django 2.0.6 on 2018-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0003_day_day_in_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
