# Generated by Django 2.0.6 on 2018-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0004_day_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
