# Generated by Django 2.0.6 on 2018-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0005_calendar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='month',
        ),
        migrations.AddField(
            model_name='calendar',
            name='day',
            field=models.ManyToManyField(blank=True, to='userscalendar.Day'),
        ),
    ]
