# Generated by Django 2.0.6 on 2018-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0006_auto_20180624_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='calendar_id',
        ),
        migrations.AddField(
            model_name='day',
            name='calendar_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
