# Generated by Django 2.0.6 on 2018-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscalendar', '0008_auto_20180624_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day_Calendar',
        ),
        migrations.AddField(
            model_name='calendar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
